export const employe = [
  {
    title: "Onboarding",
    screen: "5 Screens",
    progress: 60,
    value: "60%",
    member: "+4",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
    image2: require("../../images/users/circle3.png"),
  },
  {
    title: "App Design",
    screen: "14 Screens",
    progress: 30,
    value: "30%",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
  },

  {
    title: "Onboarding",
    screen: "5 Screens",
    progress: 60,
    value: "60%",
    member: "+7",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
    image2: require("../../images/users/circle3.png"),
  },
  {
    title: "Content to main Page",
    screen: "We get new content",
    progress: 21,
    value: "21%",
    image: require("../../images/users/circle1.png"),
  },
  {
    title: "Wireframes",
    screen: "Create prototypes for all Pages",
    progress: 69,
    value: "69%",
    member: "+4",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
    image2: require("../../images/users/circle3.png"),
  },
  {
    title: "Stripe payment implementation",
    screen: "Bug fix",
    progress: 45,
    value: "45%",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
  },
  {
    title: "Moodboard",
    screen: "Collect references",
    progress: 79,
    value: "79%",
    member: "+4",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
    image2: require("../../images/users/circle3.png"),
  },
  {
    title: "Persona research",
    screen: "Need to do user research",
    progress: 84,
    value: "84%",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
  },
  {
    title: "Core functionality of the app",
    screen: "Feature",
    progress: 30,
    value: "30%",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
  },
  {
    title: "Logo Design",
    screen: "Create logo type",
    progress: 89,
    value: "89%",
    member: "+4",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
    image2: require("../../images/users/circle3.png"),
  },
  {
    title: "Branding color",
    screen: "2 option with color sceme",
    progress: 84,
    value: "84%",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
  },
  {
    title: "Landing Page",
    screen: "Put some description here",
    progress: 60,
    value: "60%",
    member: "+4",
    image: require("../../images/users/circle1.png"),
    image1: require("../../images/users/circle2.png"),
    image2: require("../../images/users/circle3.png"),
  },
];
